### PR TITLE
Update to Nuxt v1.0-rc11, fix templates, add 404 error.

### PR DESCRIPTION
**Pull request by qm3ster**
It not only builds, but even renders :rofl:

### CODE REVIEW

**Comment by atinux** [comment]
Great job @qm3ster :clap:

**Comment by qm3ster** [comment]
We need to push this to https://nuxt-micro.now.sh
I assume that's @vuchl?

**Comment by qm3ster** [comment]
I don't know which templating system (vue-cli, sao, yeoman, etc.) will be used going forward (I least of all prefer a homebrew solution, which, in my opinion, is scope creep and *not invented here syndrome*. Leave others to worry about that.)
Anyway, I believe we should join the `koa`, `express` and `micro` into one template with a choice, to make maintenance easier and maintain style/feature parity going forward.
With the maintainance reduced 3x, it would not be such an outrageous idea to add tests.

Later on, perhaps nuxtent can be added.

Whether a choice of starter-style bare nuxt belongs in there too remains to be seen.

Does this seem reasonable? If it is desirable, I will attempt.

**Comment by atinux** [comment]
This is the way going forward indeed @qm3ster 

I think we may have only one repo for different template, you can take a look at https://github.com/nuxt-community/create-nuxt-app

**Comment by vuchl** [comment]
Will push a new version tonight!

**Comment by vuchl** [comment]
It's live! Thanks for the effort @qm3ster! Nice to see some one help out here.

**Pull request merged**
